name: Argos CI Screenshots

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build the website
        run: npm run build

      - name: Take screenshots with Playwright
        run: npx playwright test

      - name: Upload screenshots to Argos
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
        run: npm argos upload ./screenshots
